from django.contrib import admin
from . models import *
# Register your models here.

admin.site.register(Country_Codes)
admin.site.register(State)
admin.site.register(District)
admin.site.register(User)
admin.site.register(Franchise_Type)
admin.site.register(Franchisee)
admin.site.register(ServiceProvider)
admin.site.register(ServiceRegister)
admin.site.register(Category)
admin.site.register(Subcategory)
admin.site.register(Collar)
admin.site.register(Service_Type)
admin.site.register(Ad_category)
admin.site.register(Ad_Management)
# admin.site.register(Notification)
# admin.site.register(Ads)
admin.site.register(Dealer)
admin.site.register(Complaint)
admin.site.register(ServiceRequest)
admin.site.register(Customer)
admin.site.register(Payment)
admin.site.register(Invoice)
admin.site.register(BlockedUser)