# Generated by Django 5.1.1 on 2024-11-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='service_request',
        ),
        migrations.RemoveField(
            model_name='declineservicemodel',
            name='service_requests',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='service_register',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='service_request',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_provider',
        ),
        migrations.AlterField(
            model_name='ad_management',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_images/'),
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='CustomerReview',
        ),
        migrations.DeleteModel(
            name='DeclineServiceModel',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
